apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose-kubernetes.yml
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: database
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: atsea
        - name: POSTGRES_PASSWORD_FILE
          value: /run/secrets/postgres_password
        - name: POSTGRES_USER
          value: gordonuser
#        image: atsea_db
        image: 368863656547.dkr.ecr.eu-central-1.amazonaws.com/database:TAG
        name: database
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:                       
        - mountPath: /run/secrets
          name: secrets-mount
          # readOnly: true
      restartPolicy: Always
      volumes:
      - name: secrets-mount
        secret:
          secretName: secrets
          items:
          - key: postgres-password
            path: postgres_password
status: {}
