apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose-kubernetes.yml
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: payment-gateway
  name: payment-gateway
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: payment-gateway
    spec:
      containers:
#      - image: payment-gateway
      - image: 368863656547.dkr.ecr.eu-central-1.amazonaws.com/payment-gateway:TAG
        name: payment-gateway
        resources: {}
        volumeMounts:                       
        - mountPath: /run/secrets
          name: secrets-mount
          # readOnly: true
      restartPolicy: Always
      volumes:
      - name: secrets-mount
        secret:
          secretName: secrets
          items:
          - key: payment-token
            path: payment_token
status: {}
