#################### Deployment payment-gateway
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kompose.cmd: kompose convert --file docker-compose-kubernetes.yml
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: 2018-03-27T10:52:57Z
  generation: 1
  labels:
    io.kompose.service: payment-gateway
  name: payment-gateway
  namespace: default
  resourceVersion: "543"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/payment-gateway
  uid: 02980d1a-31ad-11e8-813c-02b0290a3f2c
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: payment-gateway
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: payment-gateway
    spec:
      containers:
      - image: 368863656547.dkr.ecr.eu-central-1.amazonaws.com/payment-gateway:TAG
        imagePullPolicy: IfNotPresent
        name: payment-gateway
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /run/secrets
          name: secrets-mount
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: secrets-mount
        secret:
          defaultMode: 420
          items:
          - key: payment-token
            path: payment_token
          secretName: secrets
status:

