#################### Deployment appserver
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kompose.cmd: kompose convert --file docker-compose-kubernetes.yml
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: 2018-03-27T10:52:57Z
  generation: 1
  labels:
    io.kompose.service: appserver
  name: appserver
  namespace: default
  resourceVersion: "575"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/appserver
  uid: 028cd15d-31ad-11e8-813c-02b0290a3f2c
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: appserver
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  progressDeadlineSeconds: 10
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: appserver
    spec:
      containers:
      - image: 368863656547.dkr.ecr.eu-central-1.amazonaws.com/appserver:TAG
        imagePullPolicy: IfNotPresent
        name: appserver
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 5005
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /run/secrets
          name: secrets-mount
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: secrets-mount
        secret:
          defaultMode: 420
          items:
          - key: postgres-password
            path: postgres_password
          secretName: secrets
status:


